services:
  - type: web
    name: crm-medico
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        fromDatabase:
          name: crm-medico-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: ".onrender.com"

databases:
  - name: crm-medico-db
    databaseName: crm_medico
    user: crm_medico
